/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/api": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** главная страница */
		get: operations["AppController_main"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/otps": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** страница с отп кодами */
		get: operations["AppController_otps"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/android/loans": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** получить займы */
		get: operations["AndroidSampleController_getLoanFeed"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/android/loans/{loanId}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** получить займ */
		get: operations["AndroidSampleController_getFullLoan"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/tester/session": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** получить сессию пользователя */
		get: operations["TesterController_session"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/tester/profile": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/** обновить профиль пользователя */
		patch: operations["TesterController_updateProfile"];
		trace?: never;
	};
	"/api/tester/auth/otp": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** создание отп кода */
		post: operations["TesterController_createOtp"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/tester/signin": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** авторизация */
		post: operations["TesterController_signin"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/users/signin": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Авторизация */
		post: operations["UsersController_signin"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/users/profile": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/** Обновить профиль пользователя */
		patch: operations["UsersController_updateProfile"];
		trace?: never;
	};
	"/api/users/session": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Получить сессию пользователя */
		get: operations["UsersController_session"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/auth/otp": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Создание отп кода */
		post: operations["OtpsController_createOtp"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/cinema/films": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Получить список фильмов */
		get: operations["CinemaController_getCinemaToday"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/cinema/film/{filmId}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Получить фильм */
		get: operations["CinemaController_getFilm"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/cinema/film/{filmId}/schedule": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Получить расписание фильма */
		get: operations["CinemaController_getFilmSchedule"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/cinema/payment": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Оплатить билеты */
		post: operations["CinemaController_createCinemaPayment"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/cinema/orders": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Получить заказы */
		get: operations["CinemaController_getCinemaOrders"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/cinema/orders/cancel": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/** Отменить заказ */
		put: operations["CinemaController_cancelCinemaOrder"];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/delivery/points": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Получить пункты выдачи */
		get: operations["DeliveryController_getPoints"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/delivery/package/types": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Получить типы посылок */
		get: operations["DeliveryController_getPackageTypes"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/delivery/calc": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Расчет доставки */
		post: operations["DeliveryController_calculateDelivery"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/delivery/order": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Создание заявки доставки */
		post: operations["DeliveryController_createOrder"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/delivery/orders": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Получить все заявки на доставку */
		get: operations["DeliveryController_getDeliveries"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/delivery/orders/{orderId}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Получить заявку на доставку */
		get: operations["DeliveryController_getDelivery"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/delivery/orders/cancel": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/** Отменить доставку */
		put: operations["DeliveryController_cancelDeliveryOrder"];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/cars/info": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Получить все автомобили */
		get: operations["CarsController_getCars"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/cars/info/{carId}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Получить автомобиль */
		get: operations["CarsController_getCar"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/cars/rent": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Получить все аренды */
		get: operations["CarsController_getCarRents"];
		put?: never;
		/** Арендовать автомобиль */
		post: operations["CarsController_createCarRent"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/cars/rent/{carRentId}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Получить аренду */
		get: operations["CarsController_getCarRent"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/cars/rent/cancel": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/** Отменить аренду */
		put: operations["CarsController_cancelCarRent"];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/pizza/catalog": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Получить пиццы */
		get: operations["PizzaController_getPizzasCatalog"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/pizza/payment": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Оплатить корзину */
		post: operations["PizzaController_createPizzaPayment"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/pizza/orders": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Получить все заказы */
		get: operations["PizzaController_getPizzaOrders"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/pizza/orders/{orderId}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Получить заказ */
		get: operations["PizzaController_getPizzaOrder"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/pizza/orders/cancel": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/** Отменить заказ */
		put: operations["PizzaController_cancelPizzaOrder"];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		LoanFeedItem: {
			/**
			 * @description Идентификатор займа
			 * @example 1
			 */
			id: number;
			/**
			 * @description Имя
			 * @example Борис
			 */
			first_name: string;
			/**
			 * @description Фамилия
			 * @example Михеев
			 */
			last_name: string;
			/**
			 * @description Сумма кредита
			 * @example 15000
			 */
			amount: number;
			/**
			 * @description Процентная ставка
			 * @example 1.9
			 */
			percent: number;
			/**
			 * @description Процентная ставка
			 * @example APPROVED
			 * @enum {string}
			 */
			status: "APPROVED" | "REGISTERED" | "REJECTED";
		};
		Loan: {
			/**
			 * @description Идентификатор займа
			 * @example 1
			 */
			id: number;
			/**
			 * @description Имя
			 * @example Борис
			 */
			first_name: string;
			/**
			 * @description Фамилия
			 * @example Михеев
			 */
			last_name: string;
			/**
			 * @description Сумма кредита
			 * @example 15000
			 */
			amount: number;
			/**
			 * @description Процентная ставка
			 * @example 1.9
			 */
			percent: number;
			/**
			 * @description Процентная ставка
			 * @example APPROVED
			 * @enum {string}
			 */
			status: "APPROVED" | "REGISTERED" | "REJECTED";
			/**
			 * @description Номер телефона
			 * @example +77259786293
			 */
			phone: string;
			/**
			 * @description Дата выдачи кредита
			 * @example 2024-05-25T12:01:44Z
			 */
			date: string;
			/**
			 * @description Срок кредита
			 * @example 20
			 */
			period: number;
		};
		User: {
			/** @description ID пользователя */
			_id: string;
			/**
			 * @description Номер телефона
			 * @example 89990009999
			 */
			phone: string;
			/**
			 * @description Имя
			 * @example firstname
			 */
			firstname?: string;
			/**
			 * @description Отчество
			 * @example middlename
			 */
			middlename?: string;
			/**
			 * @description Фамилия
			 * @example lastname
			 */
			lastname?: string;
			/**
			 * @description Почта
			 * @example email@gmail.com
			 */
			email?: string;
			/**
			 * @description Город
			 * @example city
			 */
			city?: string;
		};
		SessionResponse: {
			/** @description Статус запроса */
			success: boolean;
			/** @description Причина ошибки */
			reason?: string;
			/** @description Пользователь */
			user: components["schemas"]["User"];
		};
		UpdateProfileProfileDto: {
			/**
			 * @description Имя
			 * @example firstname
			 */
			firstname?: string;
			/**
			 * @description Отчество
			 * @example middlename
			 */
			middlename?: string;
			/**
			 * @description Фамилия
			 * @example lastname
			 */
			lastname?: string;
			/**
			 * @description Почта
			 * @example email@gmail.com
			 */
			email?: string;
			/**
			 * @description Город
			 * @example city
			 */
			city?: string;
		};
		UpdateProfileDto: {
			/** @description Данные пользователя */
			profile: components["schemas"]["UpdateProfileProfileDto"];
			/**
			 * @description Номер телефона
			 * @example 89990009999
			 */
			phone: string;
		};
		UpdateProfileResponse: {
			/** @description Статус запроса */
			success: boolean;
			/** @description Причина ошибки */
			reason?: string;
			/** @description Пользователь */
			user: components["schemas"]["User"];
		};
		CreateOtpDto: {
			/** @example 89990009999 */
			phone: string;
		};
		OtpResponse: {
			/** @description Статус запроса */
			success: boolean;
			/** @description Причина ошибки */
			reason?: string;
			/**
			 * @description Время запроса повторного отп кода в мс
			 * @example 120000
			 */
			retryDelay: number;
		};
		SignInDto: {
			/**
			 * @description Номер телефона
			 * @example 89990009999
			 */
			phone: string;
			/**
			 * @description Отп код
			 * @example 345231
			 */
			code: number;
		};
		SignInResponse: {
			/** @description Статус запроса */
			success: boolean;
			/** @description Причина ошибки */
			reason?: string;
			/** @description Пользователь */
			user: components["schemas"]["User"];
			/** @description Пользовательский токен */
			token: string;
		};
		FilmStaff: {
			/**
			 * @description Идентификатор персоны
			 * @example 1
			 */
			id: string;
			/**
			 * @description Список профессий
			 * @enum {string}
			 */
			professions: "ACTOR" | "DIRECTOR";
			/** @description Полное имя персоны */
			fullName: string;
		};
		FilmUserRating: {
			/**
			 * @description Рейтинг кинопоиск
			 * @example 10
			 */
			kinopoisk: string;
			/**
			 * @description Рейтинг imdb
			 * @example 10
			 */
			imdb: string;
		};
		Country: {
			name: string;
			code: string;
			code2: string;
			id: number;
		};
		Film: {
			/**
			 * @description Идентификатор фильма
			 * @example 1
			 */
			id: string;
			/** @description Название фильма */
			name: string;
			/** @description Оригинальное название */
			originalName: string;
			/** @description Описание фильма */
			description: string;
			/** @description Дата выхода */
			releaseDate: string;
			/** @description Актеры */
			actors: components["schemas"]["FilmStaff"][];
			/** @description Режиссер */
			directors: components["schemas"]["FilmStaff"][];
			/** @description Продолжительность */
			runtime: number;
			/**
			 * @description Возрастное ограничение
			 * @enum {string}
			 */
			ageRating: "G" | "PG" | "PG13" | "R" | "NC17";
			genres: string[];
			/** @description Рейтинг пользователей */
			userRatings: components["schemas"]["FilmUserRating"];
			/** @description Изображение фильма */
			img: string;
			/** @description Страна */
			country?: components["schemas"]["Country"] | null;
		};
		FilmsResponse: {
			/** @description Статус запроса */
			success: boolean;
			/** @description Причина ошибки */
			reason?: string;
			/** @description Фильмы */
			films: components["schemas"]["Film"][];
		};
		FilmResponse: {
			/** @description Статус запроса */
			success: boolean;
			/** @description Причина ошибки */
			reason?: string;
			/** @description Фильм */
			film: components["schemas"]["Film"];
		};
		FilmHall: {
			/**
			 * @description Название зала
			 * @example red
			 */
			name: string;
			/**
			 * @description Места в зале
			 * @example [
			 *       [
			 *         {
			 *           "type": "ECONOM",
			 *           "price": 100
			 *         }
			 *       ]
			 *     ]
			 */
			places: unknown[][];
		};
		FilmScheduleSeance: {
			/**
			 * @description Время сеанса
			 * @example 12:00
			 */
			time: string;
			/** @description Зал */
			hall: components["schemas"]["FilmHall"];
		};
		FilmSchedule: {
			/**
			 * @description Дата
			 * @example 01.01.2024
			 */
			date: string;
			/** @description Сеансы */
			seances: components["schemas"]["FilmScheduleSeance"][];
		};
		ScheduleResponse: {
			/** @description Статус запроса */
			success: boolean;
			/** @description Причина ошибки */
			reason?: string;
			/** @description Расписание */
			schedules: components["schemas"]["FilmSchedule"];
		};
		CreatePaymentPersonDto: {
			/**
			 * @description Имя
			 * @example firstname
			 */
			firstname: string;
			/**
			 * @description Фамилия
			 * @example lastname
			 */
			lastname: string;
			/**
			 * @description Отчество
			 * @example middlename
			 */
			middlename: string;
			/**
			 * @description Телефон
			 * @example 89990009999
			 */
			phone: string;
		};
		CreatePaymentDebitCardDto: {
			/**
			 * @description Номер карты
			 * @example 1111 1111
			 */
			pan: string;
			/**
			 * @description Срок действие карты
			 * @example 11/11
			 */
			expireDate: string;
			/**
			 * @description Код карты
			 * @example 111
			 */
			cvv: string;
		};
		CreatePaymentSeanceDto: {
			/**
			 * @description Дата сеанса
			 * @example 29.06.23
			 */
			date: string;
			/**
			 * @description Время сеанса
			 * @example 10:00
			 */
			time: string;
		};
		CreatePaymentTicketsDto: {
			/**
			 * @description Ряд
			 * @example 1
			 */
			row: number;
			/**
			 * @description Место
			 * @example 1
			 */
			column: number;
		};
		CreateCinemaPaymentDto: {
			/** @description Идентификатор фильма */
			filmId: string;
			/** @description Покупатель */
			person: components["schemas"]["CreatePaymentPersonDto"];
			/** @description Банковская карта */
			debitCard: components["schemas"]["CreatePaymentDebitCardDto"];
			/** @description Сеанс фильма */
			seance: components["schemas"]["CreatePaymentSeanceDto"];
			/** @description Билеты */
			tickets: components["schemas"]["CreatePaymentTicketsDto"][];
		};
		CinemaTicketSeance: {
			/**
			 * @description Дата сеанса
			 * @example 29.06.23
			 */
			date: string;
			/**
			 * @description Время сеанса
			 * @example 10:00
			 */
			time: string;
		};
		CinemaTicket: {
			/** @description ID билета */
			_id: string;
			/** @description Идентификатор фильма */
			filmId: string;
			/** @description Идентификатор заказа */
			orderId: string;
			/**
			 * @description Ряд
			 * @example 1
			 */
			row: number;
			/**
			 * @description Место
			 * @example 1
			 */
			column: number;
			/** @description Сеанс фильма */
			seance: components["schemas"]["CinemaTicketSeance"];
			/**
			 * @description Телефон
			 * @example 89990009999
			 */
			phone: string;
			/**
			 * @description Статус билета
			 * @enum {string}
			 */
			status: "PAYED" | "CANCELED";
		};
		FilmPerson: {
			/**
			 * @description Имя
			 * @example firstname
			 */
			firstname: string;
			/**
			 * @description Фамилия
			 * @example lastname
			 */
			lastname: string;
			/**
			 * @description Отчество
			 * @example middlename
			 */
			middlename: string;
			/**
			 * @description Телефон
			 * @example 89990009999
			 */
			phone: string;
		};
		CinemaOrder: {
			/** @description ID заказа */
			_id: string;
			/** @description Название фильма */
			film: components["schemas"]["Film"];
			/** @description Номер заказа */
			orderNumber: number;
			/** @description Билеты */
			tickets: components["schemas"]["CinemaTicket"][];
			/** @description Данные пользователя */
			person: components["schemas"]["FilmPerson"];
			/**
			 * @description Статус заказа
			 * @enum {string}
			 */
			status: "PAYED" | "CANCELED";
		};
		PaymentResponse: {
			/** @description Статус запроса */
			success: boolean;
			/** @description Причина ошибки */
			reason?: string;
			/** @description Заказ */
			order: components["schemas"]["CinemaOrder"];
		};
		CinemaOrdersResponse: {
			/** @description Статус запроса */
			success: boolean;
			/** @description Причина ошибки */
			reason?: string;
			/** @description Заказы */
			orders: components["schemas"]["CinemaOrder"][];
		};
		CancelCinemaOrderDto: {
			/** @description Идентификатор билета */
			orderId: string;
		};
		BaseResponse: {
			/** @description Статус запроса */
			success: boolean;
			/** @description Причина ошибки */
			reason?: string;
		};
		DeliveryPoint: {
			/**
			 * @description Индентификатор пункта
			 * @example 1
			 */
			id: string;
			/**
			 * @description Название пункта
			 * @example name
			 */
			name: string;
			/**
			 * @description Широта
			 * @example latitude
			 */
			latitude: number;
			/**
			 * @description Долгота
			 * @example longitude
			 */
			longitude: number;
		};
		DeliveryPointsResponse: {
			/** @description Статус запроса */
			success: boolean;
			/** @description Причина ошибки */
			reason?: string;
			/** @description Пункты доставки */
			points: components["schemas"]["DeliveryPoint"][];
		};
		DeliveryPackageType: {
			/**
			 * @description Индентификатор типа посылки
			 * @example envelope
			 */
			id: string;
			/**
			 * @description Название типа посылки
			 * @example name
			 */
			name: string;
			/**
			 * @description Длина посылки
			 * @example length
			 */
			length: number;
			/**
			 * @description Ширина посылки
			 * @example width
			 */
			width: number;
			/**
			 * @description Длина посылки
			 * @example weight
			 */
			weight: number;
			/**
			 * @description Высота посылки
			 * @example length
			 */
			height: number;
		};
		DeliveryPackageTypesResponse: {
			/** @description Статус запроса */
			success: boolean;
			/** @description Причина ошибки */
			reason?: string;
			/** @description Типы */
			packages: components["schemas"]["DeliveryPackageType"][];
		};
		CalculateDeliveryPackageDto: {
			/**
			 * @description Длина посылки
			 * @example 10
			 */
			length: number;
			/**
			 * @description Ширина посылки
			 * @example 10
			 */
			width: number;
			/**
			 * @description Длина посылки
			 * @example 10
			 */
			weight: number;
			/**
			 * @description Высота посылки
			 * @example 10
			 */
			height: number;
		};
		CalculateDeliveryPointDto: {
			/**
			 * @description Широта
			 * @example 56.8389
			 */
			latitude: number;
			/**
			 * @description Долгота
			 * @example 60.6057
			 */
			longitude: number;
		};
		CalculateDeliveryDto: {
			/** @description Поссылка */
			package: components["schemas"]["CalculateDeliveryPackageDto"];
			/** @description Город отправки */
			senderPoint: components["schemas"]["CalculateDeliveryPointDto"];
			/** @description Город получения */
			receiverPoint: components["schemas"]["CalculateDeliveryPointDto"];
		};
		DeliveryOption: {
			/**
			 * @description Индентификатор опции доставки
			 * @example 1
			 */
			id: string;
			/**
			 * @description Цена доставки в копейках
			 * @example 10000
			 */
			price: number;
			/**
			 * @description Количество дней доставки
			 * @example 2
			 */
			days: number;
			/**
			 * @description Название опции отправки
			 * @example name
			 */
			name: string;
			/**
			 * @description Тип доставки
			 * @example type
			 * @enum {string}
			 */
			type: "DEFAULT" | "EXPRESS";
		};
		CalculateDeliveryResponse: {
			/** @description Статус запроса */
			success: boolean;
			/** @description Причина ошибки */
			reason?: string;
			/** @description Опции доставки */
			options: components["schemas"]["DeliveryOption"][];
		};
		CreateDeliveryOrderSenderAddressDto: {
			/**
			 * @description Улица
			 * @example street
			 */
			street: string;
			/**
			 * @description Номер дома
			 * @example house
			 */
			house: string;
			/**
			 * @description Номер квартиры
			 * @example apartment
			 */
			apartment: string;
			/**
			 * @description Комментарий
			 * @example comment
			 */
			comment?: string;
		};
		CreateDeliveryOrderPersonDto: {
			/**
			 * @description Имя
			 * @example firstname
			 */
			firstname: string;
			/**
			 * @description Фамилия
			 * @example lastname
			 */
			lastname: string;
			/**
			 * @description Отчество
			 * @example middlename
			 */
			middlename?: string;
			/**
			 * @description Телефон
			 * @example 89990009999
			 */
			phone: string;
		};
		CreateDeliveryOrderReceiverAddressDto: {
			/**
			 * @description Улица
			 * @example street
			 */
			street: string;
			/**
			 * @description Номер дома
			 * @example house
			 */
			house: string;
			/**
			 * @description Номер квартиры
			 * @example apartment
			 */
			apartment: string;
			/**
			 * @description Комментарий
			 * @example comment
			 */
			comment?: string;
			/** @description Бесконтактная доставка */
			isNonContact?: boolean;
		};
		CreateDeliveryOrderDto: {
			/** @description Идентификатор типа посылки */
			packageId: string;
			/**
			 * @description Тип заказа
			 * @enum {string}
			 */
			optionType: "DEFAULT" | "EXPRESS";
			/** @description Идентификатор города отправки */
			senderPointId: string;
			/** @description Адрес отправителя */
			senderAddress: components["schemas"]["CreateDeliveryOrderSenderAddressDto"];
			/** @description Отправитель */
			sender: components["schemas"]["CreateDeliveryOrderPersonDto"];
			/** @description Идентификатор города получения */
			receiverPointId: string;
			/** @description Адрес получателя */
			receiverAddress: components["schemas"]["CreateDeliveryOrderReceiverAddressDto"];
			/** @description Получатель */
			receiver: components["schemas"]["CreateDeliveryOrderPersonDto"];
			/**
			 * @description Кто будет оплачивать
			 * @enum {string}
			 */
			payer: "RECEIVER" | "SENDER";
		};
		DeliverySenderAddress: {
			/**
			 * @description Улица
			 * @example street
			 */
			street: string;
			/**
			 * @description Номер дома
			 * @example house
			 */
			house: string;
			/**
			 * @description Номер квартиры
			 * @example apartment
			 */
			apartment: string;
			/**
			 * @description Комментарий
			 * @example comment
			 */
			comment: string;
		};
		DeliveryPerson: {
			/**
			 * @description Имя
			 * @example firstname
			 */
			firstname: string;
			/**
			 * @description Фамилия
			 * @example lastname
			 */
			lastname: string;
			/**
			 * @description Отчество
			 * @example middlename
			 */
			middlename: string;
			/**
			 * @description Телефон
			 * @example 89990009999
			 */
			phone: string;
		};
		DeliveryReceiverAddress: {
			/**
			 * @description Улица
			 * @example street
			 */
			street: string;
			/**
			 * @description Номер дома
			 * @example house
			 */
			house: string;
			/**
			 * @description Номер квартиры
			 * @example apartment
			 */
			apartment: string;
			/**
			 * @description Комментарий
			 * @example comment
			 */
			comment: string;
			/** @description Бесконтактная доставка */
			isNonContact?: boolean;
		};
		DeliveryOrder: {
			/** @description ID заказа */
			_id: string;
			/** @description Цена доставки */
			price: number;
			/** @description Тип посылки */
			package: components["schemas"]["DeliveryPackageType"];
			/**
			 * @description Тип доставки
			 * @enum {string}
			 */
			option: "DEFAULT" | "EXPRESS";
			/** @description Город отправки */
			senderPoint: components["schemas"]["DeliveryPoint"];
			/** @description Адрес отправителя */
			senderAddress: components["schemas"]["DeliverySenderAddress"];
			/** @description Отправитель */
			sender: components["schemas"]["DeliveryPerson"];
			/** @description Город получения */
			receiverPoint: components["schemas"]["DeliveryPoint"];
			/** @description Адрес получателя */
			receiverAddress: components["schemas"]["DeliveryReceiverAddress"];
			/** @description Получатель */
			receiver: components["schemas"]["DeliveryPerson"];
			/**
			 * @description Кто будет оплачивать
			 * @enum {string}
			 */
			payer: "RECEIVER" | "SENDER";
			/**
			 * @description Статус доставки
			 * @enum {number}
			 */
			status: 0 | 1 | 2 | 3 | 4;
			/** @description Статус отмены */
			cancellable: boolean;
		};
		DeliverResponse: {
			/** @description Статус запроса */
			success: boolean;
			/** @description Причина ошибки */
			reason?: string;
			/** @description Доставка */
			order: components["schemas"]["DeliveryOrder"];
		};
		DeliveryOrdersResponse: {
			/** @description Статус запроса */
			success: boolean;
			/** @description Причина ошибки */
			reason?: string;
			/** @description Доставки */
			orders: components["schemas"]["DeliveryOrder"][];
		};
		DeliveryOrderResponse: {
			/** @description Статус запроса */
			success: boolean;
			/** @description Причина ошибки */
			reason?: string;
			/** @description Доставка */
			order: components["schemas"]["DeliveryOrder"];
		};
		CancelDeliveryOrderDto: {
			/** @description Идентификатор доставки */
			orderId: string;
		};
		Media: {
			/** @example /static/images/cars/haval-jolion.webp */
			url: string;
			/** @example true */
			isCover: boolean;
		};
		Car: {
			/**
			 * @description ID автомобиля
			 * @example 1
			 */
			id: string;
			/**
			 * @description Название модели
			 * @example Model X
			 */
			name: string;
			/**
			 * @description Марка автомобиля
			 * @enum {string}
			 */
			brand:
				| "Haval"
				| "Hyundai"
				| "Volkswagen"
				| "Kia"
				| "Geely"
				| "Mercedes"
				| "Garden car"
				| "Grocery cart"
				| "Haier"
				| "Invalid";
			media: components["schemas"]["Media"][];
			/**
			 * @description Тип коробки передач
			 * @enum {string}
			 */
			transmission: "automatic" | "manual";
			/**
			 * @description Цена аренды в сутки
			 * @example 15000
			 */
			price: number;
			/**
			 * @description Местоположение
			 * @example Москва, ул. Пушкина 10
			 */
			location: string;
			/**
			 * @description Цвет автомобиля
			 * @enum {string}
			 */
			color: "black" | "white" | "red" | "silver" | "blue" | "grey" | "orange";
			/**
			 * @description Тип кузова
			 * @enum {string}
			 */
			bodyType: "sedan" | "suv" | "coupe" | "hatchback" | "cabriolet";
			/**
			 * @description Расположение руля
			 * @enum {string}
			 */
			steering: "left" | "right";
		};
		PaginationMeta: {
			/**
			 * @description Общее количество элементов во всех страницах
			 * @example 100
			 */
			total: number;
			/**
			 * @description Текущий номер страницы (по умолчанию 1)
			 * @example 1
			 */
			page: number;
			/**
			 * @description Количество элементов на странице (по умолчанию 10)
			 * @example 10
			 */
			limit: number;
			/**
			 * @description Общее количество доступных страниц
			 * @example 10
			 */
			totalPages: number;
		};
		CarsPaginatedResponse: {
			/** @description Статус запроса */
			success: boolean;
			/** @description Причина ошибки */
			reason?: string;
			/** @description Массив автомобилей с информацией */
			data: components["schemas"]["Car"][];
			/** @description Метаданные пагинации (общее количество, текущая страница и т.д.) */
			meta: components["schemas"]["PaginationMeta"];
		};
		BookedDateRange: {
			/**
			 * @description Дата начала аренды (timestamp)
			 * @example 1717236000000
			 */
			startDate: number;
			/**
			 * @description Дата окончания аренды (timestamp)
			 * @example 1717610400000
			 */
			endDate: number;
		};
		CarWithRents: {
			/**
			 * @description ID автомобиля
			 * @example 1
			 */
			id: string;
			/**
			 * @description Название модели
			 * @example Model X
			 */
			name: string;
			/**
			 * @description Марка автомобиля
			 * @enum {string}
			 */
			brand:
				| "Haval"
				| "Hyundai"
				| "Volkswagen"
				| "Kia"
				| "Geely"
				| "Mercedes"
				| "Garden car"
				| "Grocery cart"
				| "Haier"
				| "Invalid";
			media: components["schemas"]["Media"][];
			/**
			 * @description Тип коробки передач
			 * @enum {string}
			 */
			transmission: "automatic" | "manual";
			/**
			 * @description Цена аренды в сутки
			 * @example 15000
			 */
			price: number;
			/**
			 * @description Местоположение
			 * @example Москва, ул. Пушкина 10
			 */
			location: string;
			/**
			 * @description Цвет автомобиля
			 * @enum {string}
			 */
			color: "black" | "white" | "red" | "silver" | "blue" | "grey" | "orange";
			/**
			 * @description Тип кузова
			 * @enum {string}
			 */
			bodyType: "sedan" | "suv" | "coupe" | "hatchback" | "cabriolet";
			/**
			 * @description Расположение руля
			 * @enum {string}
			 */
			steering: "left" | "right";
			/** @description Занятые промежутки дат (timestamp) */
			rents: components["schemas"]["BookedDateRange"][];
		};
		CarResponse: {
			/** @description Статус запроса */
			success: boolean;
			/** @description Причина ошибки */
			reason?: string;
			/** @description Данные автомобиля с арендованными датами */
			data: components["schemas"]["CarWithRents"];
		};
		CreateRentDto: {
			/**
			 * @description Идентификатор автомобиля
			 * @example car123
			 */
			carId: string;
			/**
			 * @description Место получения автомобиля
			 * @example Москва, ул. Ленина, 12
			 */
			pickupLocation: string;
			/**
			 * @description Место возврата автомобиля
			 * @example Москва, ул. Тверская, 15
			 */
			returnLocation: string;
			/**
			 * @description Дата начала аренды (timestamp в миллисекундах)
			 * @example 1717236000000
			 */
			startDate: number;
			/**
			 * @description Дата окончания аренды (timestamp в миллисекундах)
			 * @example 1717610400000
			 */
			endDate: number;
			/**
			 * @description Имя арендатора
			 * @example Иван
			 */
			firstName: string;
			/**
			 * @description Фамилия арендатора
			 * @example Иванов
			 */
			lastName: string;
			/**
			 * @description Отчество арендатора
			 * @example Иванович
			 */
			middleName?: string;
			/**
			 * @description Дата рождения арендатора (ISO формат)
			 * @example 1990-01-01
			 */
			birthDate: string;
			/**
			 * @description Email арендатора
			 * @example ivan@example.com
			 */
			email: string;
			/**
			 * @description Телефон арендатора в формате 7XXXXXXXXXX
			 * @example 79876543210
			 */
			phone: string;
			/**
			 * @description Комментарий арендатора
			 * @example Позвонить за 1 час до выдачи
			 */
			comment?: string;
		};
		CarRent: {
			/** @description ID заказа */
			_id: string;
			/**
			 * @description Информация об автомобиле
			 * @example {
			 *       "id": "12",
			 *       "name": "Kia Rio 1.4 AT",
			 *       "brand": "Kia",
			 *       "img": "/static/images/cars/kia-rio-black.webp",
			 *       "transmission": "manual",
			 *       "price": 3100,
			 *       "location": "Новосибирск, ул. Ленина, 5",
			 *       "color": "black",
			 *       "bodyType": "sedan",
			 *       "steering": "left"
			 *     }
			 */
			carInfo: components["schemas"]["Car"];
			/**
			 * @description Статус брони
			 * @example 0
			 * @enum {number}
			 */
			status: 0 | 1;
			/**
			 * @description Место получения автомобиля
			 * @example Москва, ул. Ленина, 1
			 */
			pickupLocation: string;
			/**
			 * @description Место возврата автомобиля
			 * @example Москва, ул. Тверская, 10
			 */
			returnLocation: string;
			/**
			 * @description Дата начала аренды (timestamp в миллисекундах)
			 * @example 1717236000000
			 */
			startDate: number;
			/**
			 * @description Дата окончания аренды (timestamp в миллисекундах)
			 * @example 1717610400000
			 */
			endDate: number;
			/**
			 * @description Общая сумма аренды
			 * @example 25000
			 */
			totalPrice: number;
			/**
			 * @description Имя арендатора
			 * @example Иван
			 */
			firstName: string;
			/**
			 * @description Фамилия арендатора
			 * @example Иванов
			 */
			lastName: string;
			/**
			 * @description Отчество арендатора
			 * @example Иванович
			 */
			middleName?: string;
			/**
			 * @description Дата рождения арендатора
			 * @example 1990-05-10
			 */
			birthDate: string;
			/**
			 * @description Email арендатора
			 * @example ivan@example.com
			 */
			email: string;
			/**
			 * @description Телефон арендатора (совпадает с номером пользователя)
			 * @example 79991234567
			 */
			phone: string;
			/**
			 * @description Комментарий
			 * @example Позвонить за час до выдачи
			 */
			comment?: string;
		};
		CarRentResponse: {
			/** @description Статус запроса */
			success: boolean;
			/** @description Причина ошибки */
			reason?: string;
			/** @description Аренда */
			rent: components["schemas"]["CarRent"];
		};
		CarRentsResponse: {
			/** @description Статус запроса */
			success: boolean;
			/** @description Причина ошибки */
			reason?: string;
			/** @description Аренды */
			rents: components["schemas"]["CarRent"][];
		};
		CancelCarRentDto: {
			/** @description Идентификатор аренды */
			carRentId: string;
		};
		PizzaIngredient: {
			/**
			 * @description Идентификатор ингредиента
			 * @enum {string}
			 */
			type:
				| "PINEAPPLE"
				| "MOZZARELLA"
				| "PEPERONI"
				| "GREEN_PEPPER"
				| "MUSHROOMS"
				| "BASIL"
				| "CHEDDAR"
				| "PARMESAN"
				| "FETA"
				| "HAM"
				| "PICKLE"
				| "TOMATO"
				| "BACON"
				| "ONION"
				| "CHILE"
				| "SHRIMPS"
				| "CHICKEN_FILLET"
				| "MEATBALLS";
			/** @description Цена ингредиента */
			price: number;
			/** @description Изображение ингредиента */
			img: string;
		};
		PizzaSize: {
			/**
			 * @description Идентификатор размера пиццы
			 * @enum {string}
			 */
			type: "SMALL" | "MEDIUM" | "LARGE";
			/** @description Цена пиццы */
			price: number;
		};
		PizzaDough: {
			/**
			 * @description Идентификатор типа теста
			 * @enum {string}
			 */
			type: "THIN" | "THICK";
			/** @description Цена теста */
			price: number;
		};
		Pizza: {
			/**
			 * @description Идентификатор пиццы
			 * @example 1
			 */
			id: string;
			/** @description Название пиццы */
			name: string;
			/** @description Ингредиенты */
			ingredients: components["schemas"]["PizzaIngredient"][];
			/** @description Топпинги */
			toppings: components["schemas"]["PizzaIngredient"][];
			/** @description Описание пиццы */
			description: string;
			/** @description Размеры пиццы */
			sizes: components["schemas"]["PizzaSize"][];
			/** @description Тип теста */
			doughs: components["schemas"]["PizzaDough"][];
			/** @description Количество калорий */
			calories: number;
			/** @description Количество белков */
			protein: string;
			/** @description Количество жиров */
			totalFat: string;
			/** @description Количество углеводов */
			carbohydrates: string;
			/** @description Количество натрия */
			sodium: string;
			/** @description Список аллергенов */
			allergens: string[];
			/** @description Для вегетарианцев */
			isVegetarian: boolean;
			/** @description Наличие глютена */
			isGlutenFree: boolean;
			/** @description Новинка */
			isNew: boolean;
			/** @description Хит */
			isHit: boolean;
			/** @description Изображение пиццы */
			img: string;
		};
		PizzasResponse: {
			/** @description Статус запроса */
			success: boolean;
			/** @description Причина ошибки */
			reason?: string;
			/** @description Пиццы */
			catalog: components["schemas"]["Pizza"][];
		};
		CreatePizzaPaymentAddressDto: {
			/**
			 * @description Улица
			 * @example street
			 */
			street: string;
			/**
			 * @description Номер дома
			 * @example house
			 */
			house: string;
			/**
			 * @description Номер квартиры
			 * @example apartment
			 */
			apartment: string;
			/**
			 * @description Комментарий
			 * @example comment
			 */
			comment?: string;
		};
		CreatePizzaPaymentPersonDto: {
			/**
			 * @description Имя
			 * @example firstname
			 */
			firstname: string;
			/**
			 * @description Фамилия
			 * @example lastname
			 */
			lastname: string;
			/**
			 * @description Отчество
			 * @example middlename
			 */
			middlename?: string;
			/**
			 * @description Телефон
			 * @example 89990009999
			 */
			phone: string;
		};
		CreatePizzaPaymentDebitCardDto: {
			/**
			 * @description Номер карты
			 * @example 1111 1111
			 */
			pan: string;
			/**
			 * @description Срок действие карты
			 * @example 11/11
			 */
			expireDate: string;
			/**
			 * @description Код карты
			 * @example 111
			 */
			cvv: string;
		};
		OrderedPizza: {
			/**
			 * @description Идентификатор пиццы
			 * @example 1
			 */
			id: string;
			/**
			 * @description Топпинги
			 * @example [
			 *       "PINEAPPLE",
			 *       "CHEDDAR"
			 *     ]
			 */
			toppings: (
				| "PINEAPPLE"
				| "MOZZARELLA"
				| "PEPERONI"
				| "GREEN_PEPPER"
				| "MUSHROOMS"
				| "BASIL"
				| "CHEDDAR"
				| "PARMESAN"
				| "FETA"
				| "HAM"
				| "PICKLE"
				| "TOMATO"
				| "BACON"
				| "ONION"
				| "CHILE"
				| "SHRIMPS"
				| "CHICKEN_FILLET"
				| "MEATBALLS"
			)[];
			/**
			 * @description Размер пиццы
			 * @example SMALL
			 * @enum {string}
			 */
			size: "SMALL" | "MEDIUM" | "LARGE";
			/**
			 * @description Тип теста
			 * @example THIN
			 * @enum {string}
			 */
			dough: "THIN" | "THICK";
		};
		CreatePizzaPaymentDto: {
			/** @description Адрес доставки */
			receiverAddress: components["schemas"]["CreatePizzaPaymentAddressDto"];
			/** @description Данные пользователя */
			person: components["schemas"]["CreatePizzaPaymentPersonDto"];
			/** @description Банковская карта */
			debitCard: components["schemas"]["CreatePizzaPaymentDebitCardDto"];
			/** @description Пиццы */
			pizzas: components["schemas"]["OrderedPizza"][];
		};
		PizzaPerson: {
			/**
			 * @description Имя
			 * @example firstname
			 */
			firstname: string;
			/**
			 * @description Фамилия
			 * @example lastname
			 */
			lastname: string;
			/**
			 * @description Отчество
			 * @example middlename
			 */
			middlename: string;
			/**
			 * @description Телефон
			 * @example 89990009999
			 */
			phone: string;
		};
		PizzaAddress: {
			/**
			 * @description Улица
			 * @example street
			 */
			street: string;
			/**
			 * @description Номер дома
			 * @example house
			 */
			house: string;
			/**
			 * @description Номер квартиры
			 * @example apartment
			 */
			apartment: string;
			/**
			 * @description Комментарий
			 * @example comment
			 */
			comment: string;
		};
		PizzaOrder: {
			/** @description ID заказа */
			_id: string;
			/** @description Пиццы */
			pizzas: components["schemas"]["Pizza"][];
			/** @description Сумма заказа */
			totalPrice: number;
			/** @description Данные пользователя */
			person: components["schemas"]["PizzaPerson"];
			/** @description Адрес доставки */
			receiverAddress: components["schemas"]["PizzaAddress"];
			/**
			 * @description Статус доставки
			 * @enum {number}
			 */
			status: 0 | 1 | 2 | 3 | 4;
			/** @description Статус отмены */
			cancellable: boolean;
		};
		PizzaPaymentResponse: {
			/** @description Статус запроса */
			success: boolean;
			/** @description Причина ошибки */
			reason?: string;
			/** @description Доставка */
			order: components["schemas"]["PizzaOrder"];
		};
		PizzaOrdersResponse: {
			/** @description Статус запроса */
			success: boolean;
			/** @description Причина ошибки */
			reason?: string;
			/** @description Доставки */
			orders: components["schemas"]["PizzaOrder"][];
		};
		PizzaOrderResponse: {
			/** @description Статус запроса */
			success: boolean;
			/** @description Причина ошибки */
			reason?: string;
			/** @description Доставки */
			order: components["schemas"]["PizzaOrder"];
		};
		CancelPizzaOrderDto: {
			/** @description Идентификатор заказа */
			orderId: string;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	AppController_main: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	AppController_otps: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	AndroidSampleController_getLoanFeed: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description loan feed */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["LoanFeedItem"][];
				};
			};
		};
	};
	AndroidSampleController_getFullLoan: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Идентификатор займа */
				loanId: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description loan */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Loan"];
				};
			};
		};
	};
	TesterController_session: {
		parameters: {
			query?: never;
			header?: {
				authorization?: string;
			};
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description session */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SessionResponse"];
				};
			};
		};
	};
	TesterController_updateProfile: {
		parameters: {
			query?: never;
			header?: {
				authorization?: string;
			};
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["UpdateProfileDto"];
			};
		};
		responses: {
			/** @description update profile */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["UpdateProfileResponse"];
				};
			};
		};
	};
	TesterController_createOtp: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CreateOtpDto"];
			};
		};
		responses: {
			/** @description create otp */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["OtpResponse"];
				};
			};
		};
	};
	TesterController_signin: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["SignInDto"];
			};
		};
		responses: {
			/** @description signin */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SignInResponse"];
				};
			};
		};
	};
	UsersController_signin: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["SignInDto"];
			};
		};
		responses: {
			/** @description signin */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SignInResponse"];
				};
			};
		};
	};
	UsersController_updateProfile: {
		parameters: {
			query?: never;
			header?: {
				authorization?: string;
			};
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["UpdateProfileDto"];
			};
		};
		responses: {
			/** @description update profile */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["UpdateProfileResponse"];
				};
			};
		};
	};
	UsersController_session: {
		parameters: {
			query?: never;
			header?: {
				authorization?: string;
			};
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description session */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SessionResponse"];
				};
			};
		};
	};
	OtpsController_createOtp: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CreateOtpDto"];
			};
		};
		responses: {
			/** @description create otp */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["OtpResponse"];
				};
			};
		};
	};
	CinemaController_getCinemaToday: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description films */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["FilmsResponse"];
				};
			};
		};
	};
	CinemaController_getFilm: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Идентификатор фильма */
				filmId: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description film */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["FilmResponse"];
				};
			};
		};
	};
	CinemaController_getFilmSchedule: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Идентификатор фильма */
				filmId: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description schedule */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ScheduleResponse"];
				};
			};
		};
	};
	CinemaController_createCinemaPayment: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CreateCinemaPaymentDto"];
			};
		};
		responses: {
			/** @description payment */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["PaymentResponse"];
				};
			};
		};
	};
	CinemaController_getCinemaOrders: {
		parameters: {
			query?: never;
			header?: {
				authorization?: string;
			};
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description orders */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CinemaOrdersResponse"];
				};
			};
		};
	};
	CinemaController_cancelCinemaOrder: {
		parameters: {
			query?: never;
			header?: {
				authorization?: string;
			};
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CancelCinemaOrderDto"];
			};
		};
		responses: {
			/** @description order cancel */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["BaseResponse"];
				};
			};
		};
	};
	DeliveryController_getPoints: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description points */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["DeliveryPointsResponse"];
				};
			};
		};
	};
	DeliveryController_getPackageTypes: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description package types */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["DeliveryPackageTypesResponse"];
				};
			};
		};
	};
	DeliveryController_calculateDelivery: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CalculateDeliveryDto"];
			};
		};
		responses: {
			/** @description calc */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CalculateDeliveryResponse"];
				};
			};
		};
	};
	DeliveryController_createOrder: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CreateDeliveryOrderDto"];
			};
		};
		responses: {
			/** @description order */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["DeliverResponse"];
				};
			};
		};
	};
	DeliveryController_getDeliveries: {
		parameters: {
			query?: never;
			header?: {
				authorization?: string;
			};
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description orders */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["DeliveryOrdersResponse"];
				};
			};
		};
	};
	DeliveryController_getDelivery: {
		parameters: {
			query?: never;
			header?: {
				authorization?: string;
			};
			path: {
				/** @description Идентификатор доставки */
				orderId: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description order */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["DeliveryOrderResponse"];
				};
			};
		};
	};
	DeliveryController_cancelDeliveryOrder: {
		parameters: {
			query?: never;
			header?: {
				authorization?: string;
			};
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CancelDeliveryOrderDto"];
			};
		};
		responses: {
			/** @description order cancel */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["BaseResponse"];
				};
			};
		};
	};
	CarsController_getCars: {
		parameters: {
			query?: {
				/** @description Поиск */
				search?: string;
				/** @description Максимальная цена аренды */
				maxPrice?: number;
				/** @description Минимальная цена аренды */
				minPrice?: number;
				/** @description Тип трансмиссии */
				transmission?: "automatic" | "manual";
				/** @description Тип кузова автомобиля */
				bodyType?: "sedan" | "suv" | "coupe" | "hatchback" | "cabriolet";
				/** @description Марка автомобиля */
				brand?:
					| "Haval"
					| "Hyundai"
					| "Volkswagen"
					| "Kia"
					| "Geely"
					| "Mercedes"
					| "Garden car"
					| "Grocery cart"
					| "Haier"
					| "Invalid";
				/** @description Цвет автомобиля */
				color?:
					| "black"
					| "white"
					| "red"
					| "silver"
					| "blue"
					| "grey"
					| "orange";
				/** @description Количество элементов на странице (по умолчанию 10) */
				limit?: number;
				/** @description Номер текущей страницы (по умолчанию 1) */
				page?: number;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CarsPaginatedResponse"];
				};
			};
		};
	};
	CarsController_getCar: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Идентификатор автомобиля */
				carId: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description car with rents */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CarResponse"];
				};
			};
		};
	};
	CarsController_getCarRents: {
		parameters: {
			query?: never;
			header?: {
				authorization?: string;
			};
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description rents */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CarRentsResponse"];
				};
			};
		};
	};
	CarsController_createCarRent: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CreateRentDto"];
			};
		};
		responses: {
			/** @description create rent */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CarRentResponse"];
				};
			};
		};
	};
	CarsController_getCarRent: {
		parameters: {
			query?: never;
			header?: {
				authorization?: string;
			};
			path: {
				/** @description Идентификатор аренды */
				carRentId: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description rent */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CarRent"];
				};
			};
		};
	};
	CarsController_cancelCarRent: {
		parameters: {
			query?: never;
			header?: {
				authorization?: string;
			};
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CancelCarRentDto"];
			};
		};
		responses: {
			/** @description rent cancel */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["BaseResponse"];
				};
			};
		};
	};
	PizzaController_getPizzasCatalog: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description catalog */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["PizzasResponse"];
				};
			};
		};
	};
	PizzaController_createPizzaPayment: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CreatePizzaPaymentDto"];
			};
		};
		responses: {
			/** @description payment */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["PizzaPaymentResponse"];
				};
			};
		};
	};
	PizzaController_getPizzaOrders: {
		parameters: {
			query?: never;
			header?: {
				authorization?: string;
			};
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description orders */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["PizzaOrdersResponse"];
				};
			};
		};
	};
	PizzaController_getPizzaOrder: {
		parameters: {
			query?: never;
			header?: {
				authorization?: string;
			};
			path: {
				/** @description Идентификатор заказа */
				orderId: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description order */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["PizzaOrderResponse"];
				};
			};
		};
	};
	PizzaController_cancelPizzaOrder: {
		parameters: {
			query?: never;
			header?: {
				authorization?: string;
			};
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CancelPizzaOrderDto"];
			};
		};
		responses: {
			/** @description order cancel */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["BaseResponse"];
				};
			};
		};
	};
}
